* improve the error logging in the output file merging utilities [rtj]

diff --git a/hadd b/hadd
--- a/hadd
+++ b/hadd
@@ -12,3 +12,8 @@ if [ ! -d /group/halld ]; then
 fi
 
 $ROOTSYS/bin/hadd $*
+retcode=$?
+if [ $retcode != 0 ]; then
+    echo "Error - corrupted root file somewhere in set $1" >&2
+    exit $retcode
+fi
diff --git a/hddmcat b/hddmcat
--- a/hddmcat
+++ b/hddmcat
@@ -19,3 +19,14 @@ if [ "$1" = "-o" ]; then
 else
     hddmcat $*
 fi
+retcode=$?
+if [ $retcode != 0 ]; then
+    while [ $# -gt 0 ]; do
+        hddmcat $1 >/dev/null
+        if [ $? != 0 ]; then
+            echo "Error - hddm output file $1 unreadable" >&2
+        fi
+        shift
+    done
+    exit $retcode
+fi
